## Strings (`str`)
Strings are immutable sequences of characters. They support indexing and slicing.

In [4]:
# Note that I intentionally did not include any comments. You should add comments to explain the code.
# Your assignment includes adding comments to all code cells.
text = "Engineering"
print(type(text))
print(len(text))
print("First character:", text[5]) # Each character is indexed, starting from 0.
print("Slice:", text[1:5])

# Your code here to print out diffent characters and slices of the string.

<class 'str'>
11
First character: e
Slice: ngin


## Lists (`list`) [ ]
Lists are ordered and mutable collections. They can contain mixed types and be nested.

In [13]:
data = [1, "temp", [6.7, 6.9]] # You should change the nested array to 5 elements.
print(type(data))
print("Second element:", data[1])
print("Nested list:", data[2]) # Do you need to change anything on this line? Why or why not?
print("Second element in the nested list:", data[2][1]) # What do you expect to see?

<class 'list'>
Second element: temp
Nested list: [6.7, 6.9]
Second element in the nested list: 6.9


## Tuples (`tuple`) ( )
Tuples are ordered and immutable collections.

In [17]:
point = (3, 4, 5, 6, 7, 8)
print(type(point))
print("X coordinate:", point[0])
# Your code here to print out different elements of the tuple.i.e, the Y or Z element.
print("Y coordinate:", point[3])

<class 'tuple'>
X coordinate: 3
Y coordinate: 6


## Sets (`set`) { }
Sets are unordered collections of unique elements.

In [19]:
sensors = {"temp", "pressure", "temp", "length", "weight"} # Add more elements to the set.
print("Set contents:", sensors)
print("Is 'temp' in sensors?", "temp" in sensors)
# Note that sets are unordered. You cannot access elements by index.
# Your code here to add more elements and check membership of other elements.
print("Is 'pressure' in sensors?", "pressure" in sensors)

Set contents: {'weight', 'temp', 'length', 'pressure'}
Is 'temp' in sensors? True
Is 'pressure' in sensors? True


## Dictionaries (`dict`) { "key1":, "key2": .....}
Dictionaries store key-value pairs and allow fast lookup using keys.

In [21]:
sensor_data = {"temp": 22.5, "pressure": 101.3} # Add more key-value pairs to the dictionary.
print("Temperature:", sensor_data["temp"])
# Your code here to print out different values using their keys and add new key-value pairs.
print("Pressure:", sensor_data["pressure"])

Temperature: 22.5
Pressure: 101.3


### Example- 🛒 Grocery Bill Calculator

Loop through a list of grocery items and their prices shown in the code. Calculate the total bill. Apply a 5% discount if the total exceeds $50. Print out the total bill and an indication on whether a discount is applied. 

Hint: You will need a for loop through this list and then a conditional statement to determine if a discount can be applied. 

In [27]:
items = {'Milk': 4.5, 'Bread': 3.2, 'Eggs': 6.0, 'Cheese': 8.5, 'Fruits': 12.0, 'Vegetables': 10.0, 'Snacks': 9.0, 'Beverages': 7.5,}
# You can add/delete items if you want

# Initialize accumulators for total price and item count
total = 0.0
total_item = 0

# Iterate through items, sum prices and count items; print each item's price
for name, price in items.items():
    total += price
    total_item += 1
    print(f"{name} costs ${price:.2f}")

# Calculate discount (5% if total exceeds $50)
discount = 0.0  # default: no discount
if total > 50.0:
    discount = total * 0.05  # 5% discount

# Print discount and final total after applying discount
print(f"Discount applied: ${discount:.2f}")

total_after_discount = total - discount
print(f"Total grocery bill is ${total_after_discount:.2f} for {total_item} items.")


Milk costs $4.50
Bread costs $3.20
Eggs costs $6.00
Cheese costs $8.50
Fruits costs $12.00
Vegetables costs $10.00
Snacks costs $9.00
Beverages costs $7.50
Discount applied: $3.04
Total grocery bill is $57.67 for 8 items.


## NumPy Arrays (`np.array( )`)
NumPy arrays are efficient for numerical data and support vectorized operations. Here is a simple example. We will dicsuss how to use NumPy Arrays more in future lectures. 

In [30]:
import numpy as np

# Create a 1D numpy array
arr1 = np.array([1, 2, 3])

# Create a 2D numpy array
arr2 = np.array([[4, 5],
                 [7, 8]])

# Print the second element of arr1 multiplied by 2
print("Second element of arr1 multiplied by 2:", arr1[1] * 2)

# Print the 2D array
print("Array 2:")
print(arr2)

Second element of arr1 multiplied by 2: 4
Array 2:
[[4 5]
 [7 8]]


In [2]:
# Create and display a 5x3 NumPy array and the array multiplied by 2.
# Import numpy here in case this cell is run before the cell that imports it.
import numpy as np

# Create a 1D list of 15 elements and reshape into a 5x3 array
arr3 = np.array([1, 2, 3, 4, 5,
                 6, 7, 8, 9, 10,
                 11, 12, 13, 14, 15]).reshape((5, 3))

# Print the original 5x3 array
print("Original 5x3 array (arr3):")
print(arr3)

# Print the entire array multiplied by 2
print("Entire array multiplied by 2:")
print(arr3 * 2)


Original 5x3 array (arr3):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
Entire array multiplied by 2:
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]
 [20 22 24]
 [26 28 30]]


## Sorting
Python lists can be sorted using the built-in `sorted()` function or the `.sort()` method.

In [1]:
numbers = [5, 2, 9, 1, 5, 6]
print("Original:", numbers)

numbers.sort()
# sorted_numbers = sorted(numbers) # uncomment this line if you want to use sorted() instead of sort()

print("Sorted:  ", numbers)
# print("Sorted:  ", sorted_numbers) # when you uncomment sorted_numbers

Original: [5, 2, 9, 1, 5, 6]
Sorted:   [1, 2, 5, 5, 6, 9]


In [2]:
# Your code here
# Make up a list (any type you want) and sort them. Print out the original and sorted lists.
# You can only use .sort() method.

numbers = [67, 69, 420, 21, 5]
print("Original:", numbers)

numbers.sort()

print("Sorted:  ", numbers)

Original: [67, 69, 420, 21, 5]
Sorted:   [5, 21, 67, 69, 420]


### Sort a list of tuples usign a *lambda* function
A `lambda` function in Python is an anonymous, single-expression function. It is defined using the `lambda` keyword and allows for the creation of small, inline functions without needing to use the def keyword or assign a name. `lambda` functions are particularly useful in situations where a small, one-off function is needed as an argument to a higher-order function (a function that takes other functions as arguments). We will discuss more in future lectures. 

In [3]:
my_list = [(1, 'apple'), (2, 'orange'), (3, 'banana')] # List of tuples
my_list.sort(key= lambda item: item[0]) # Sorts by the first element of each tuple
print("Sorted by first element:", my_list)
# You should change the list an print out the sorted list based on different elements.

Sorted by first element: [(1, 'apple'), (2, 'orange'), (3, 'banana')]


In [4]:
# Your code here.  
# Make up a list of tuples (anything you want) and sort them. 
# Print out the original and sorted lists.
my_list = [(1, 'book'), (2, 'pencil'), (3, 'eraser'), (4, 'ruler')]
my_list.sort(key= lambda item: item[0])
print("Sorted by first element:", my_list)

Sorted by first element: [(1, 'book'), (2, 'pencil'), (3, 'eraser'), (4, 'ruler')]


### Sorting Dictionaries by Values
Need to use `sorted()` with a `lambda` function to sort *dictionary* items by value. Cannot use `.sort`

In [5]:
grades = {'Alice': 88, 'Bob': 95, 'Charlie': 78} # dictionary items
sorted_grades = sorted(grades.items(), key=lambda x: x[1])
print("Sorted by value:", sorted_grades)

Sorted by value: [('Charlie', 78), ('Alice', 88), ('Bob', 95)]


In [6]:
# Your code here
# Make up an array of dictionary items (any type you want) and sort them.
# Print out the original and sorted lists.
bench_pr = {'Henry': 185, 'Fred': 135, 'Ramiro': 225, 'Angel': 45}
sorted_bench_pr = sorted(bench_pr.items(), key=lambda x: x[1])
print("Sorted by value:", sorted_bench_pr)

Sorted by value: [('Angel', 45), ('Fred', 135), ('Henry', 185), ('Ramiro', 225)]


## TXT Files


### Write a TXT file

The code below creates a text file called *test.txt* and write a couple lines in it. 
Check and see where this file is located on your desk!

In [7]:
f = open('test.txt', 'w') # opened a file object *f* with the file name 'test.txt'; "w+" for the mode indicates write
for i in range(5):
    f.write(f"This is line {i+1}\n") #write 5 lines. Note the newline '\n' at the end of the string.
    
f.close() # It is good practice to close the file using f.close() in the end.

# Check your local folder and see whether the file 'test.txt' is created and contains the 5 lines.

## Append to a TXT file
We can also append some string to the *test.txt* file. It is very similar to how we write the file, with only one difference - change the mode to 'a' instead. 

In [8]:
f = open('test.txt', 'a')
f.write(f"This is another line\n") #append a line
# Try to add more lines 
f.close()
# Check your local folder and see whether the file 'test.txt' is updated with the new line.
# Append more lines as needed.

## Reading a TXT File
Let's read in the *test.txt* file we created above and store all the contents in the file to a variable *content*.

In [ ]:
# Add comments to explain the code.
f = open('./test.txt', 'r') #Opening the file we created
content = f.read() #Using f.read to view the content in the file
f.close() #Now we close the file knowing what's inside
print(content)

This is line 1
This is line 2
This is line 3
This is line 4
This is line 5
This is another line



In [10]:
# Another way to read a file using 'with' statement
with open('test.txt', 'r') as f: 
    content = f.read()
f.close()
print(content)

This is line 1
This is line 2
This is line 3
This is line 4
This is line 5
This is another line



In [12]:
# Try to generate a new TXT file and write some data into it.
# Your code here
f = open('random.txt', 'w') 

for i in range(5):
    f.write(f"Hello self {i+1}\n") 
    
f.close()


In [13]:
# Try to read the TXT file you just created and print out the content.
# Your code here
f = open('./random.txt', 'r')
content = f.read()
f.close()
print(content)

Hello self 1
Hello self 2
Hello self 3
Hello self 4
Hello self 5



## Dealing with numbers and arrays

Since we are working with numerical methods later, and many times, we work with the numbers or arrays. We could use the above methods to save the numbers or arrays to a file and read it back to the memory. But it is not so convenient this way. Instead, commonly we use the *numpy* package to directly save/read an array. For example, you can use np.savetxt & np.loadtxt as shown below. 


In [11]:
# Store an array to a file named *my_arr.txt* 
# and read it back to a variable called *my_arr*. 
import numpy as np
arr = np.array([[1.25, 2.21, 3.05], 
                [4.13, 5.75, 6.92]]) # Use np.array to create the array.
np.savetxt('my_arr.txt', arr, fmt='%.2f') #Save the array to a text file w/format and headers specified
my_arr = np.loadtxt('my_arr.txt')
print(my_arr)
# See whether the file 'my_arr.txt' is created in your local folder.

[[1.25 2.21 3.05]
 [4.13 5.75 6.92]]


In [ ]:
# Try to make a 3x3 matrix using np.array and save it to a file named *my_matrix.txt*.
# Then read it back to a variable called *my_matrix* and print it out.

import numpy as np  

arr = np.array([
    [5.32, 4.42, 2.40],
    [3.78, 8.27, 6.12],
    [7.91, 1.32, 9.69]])

np.savetxt('my_matrix.txt', arr, fmt='%.2f')

my_matrix = np.loadtxt('my_matrix.txt')

print(my_matrix)

[[5.32 4.42 2.4 ]
 [3.78 8.27 6.12]
 [7.91 1.32 9.69]]


## Write and open a CSV file
CSV files store tabular data. Useful for lists, dictionaries, and arrays.
A simple example of using the random number generator to generate 100 rows and 5 columns of data 

In [14]:
import numpy as np
data = np.random.random((100,3))
np.savetxt('test.csv', data, fmt = '%.2f', delimiter=',', header = 'c1, c2, c3')
# See whether the file 'test.csv' is created in your local folder.

## Read a CSV File
### Use *np.loadtxt* function
We could read in the csv file using the *np.loadtxt* function. Let's read in the csv file we just saved to the disk to a variable *my_csv*, and output the first 5 rows. Note here we use the *delimiter* again to specify that the data in the file is separated by commas. 

In [15]:
my_csv = np.loadtxt('./test.csv', delimiter=',')
my_csv[:10]

array([[0.32, 0.74, 0.63],
       [0.69, 0.9 , 0.39],
       [0.96, 0.31, 0.63],
       [0.13, 0.83, 0.93],
       [0.1 , 0.24, 0.68],
       [0.81, 0.56, 0.33],
       [0.1 , 0.15, 0.34],
       [0.4 , 0.14, 0.38],
       [0.59, 0.35, 0.52],
       [0.82, 0.71, 0.28]])

### Use *np.genfromtxt* to read the file and print out the data.

In [ ]:
# Download the example.csv file from Canvas and put it in your local folder.
# Data include: Name (string), Age (int), City (string)
import numpy as np
data = np.genfromtxt('example.csv', delimiter=',', names=True, dtype=None, encoding='utf-8')
# print(data) # Data contains names, ages and cities.
ages = data['Age']
print("Ages:", ages)
# Your code here to read the file and print out the data other than the "Age" column.

#Couldn't find file :(

FileNotFoundError: example.csv not found.

### Sort data in CSV file and write the sorted data in a new CVS file

In [17]:
# Try to add more lines of data to example.csv by hand and sort the data based on age.

# Sort data based on ages (descending)
sorted_data = np.sort(data, order='Age')[::-1]
print(sorted_data)

# Header for the CSV file
header = 'Name, Age, City'

# Save the structured array to CSV.
# Use one format specifier per field in the structured array: Name (string), Age (int), City (string).
# Provide fmt as a list so the number of formats matches the number of columns.
np.savetxt('sorted_examples.csv', sorted_data, fmt=['%s','%d','%s'], delimiter=',', header=header, comments='')

ValueError: Cannot specify order when the array has no fields.

In [ ]:
# Use the random data generation code to create a CSV file of 100 data, between 0 to 1000. 
# Sort them and write them to a new "sorted" CSV file.
# You need to upload the original CSV file and the sorted CSV file. 